[package]
name = "botnvidia"
version.workspace = true
edition = "2021"
description = "General Bots NVIDIA GPU monitoring module"
license = "MIT"
authors = ["General Bots"]
repository = "https://github.com/generalbots/generalbots"

[dependencies]
botlib = { path = "../../../botlib" }
anyhow = { workspace = true }
sysinfo = { workspace = true }

[lints]
workspace = true
