[package]
name = "botintegrations"
version.workspace = true
edition = "2021"

[dependencies]
aws-credential-types = { workspace = true }
aws-sigv4 = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
botcore = { workspace = true }
botcoresecrets = { workspace = true }
botsecurity-auth = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde", "clock"] }
diesel = { workspace = true, features = ["postgres", "uuid", "chrono", "serde_json", "r2d2", "numeric", "32-column-tables"] }
http = { workspace = true }
log = { workspace = true }
quick-xml = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls", "json"] }
rust_decimal = { workspace = true, features = ["serde-with-str", "db-diesel2-postgres"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
urlencoding = { workspace = true }
uuid = { workspace = true, features = ["v4", "v7", "serde"] }
hmac = { workspace = true }
sha2 = { workspace = true }
