-- 6.5.50-multitenant-scope (rollback)
-- Drop branch_id indexes and columns added by the tenant-scoping migration.
DROP INDEX IF EXISTS idx_hr_employees_branch;
DROP INDEX IF EXISTS idx_hr_recruitment_branch;
DROP INDEX IF EXISTS idx_hr_attendance_branch;
DROP INDEX IF EXISTS idx_hr_review_cycles_branch;
DROP INDEX IF EXISTS idx_hr_goals_branch;
DROP INDEX IF EXISTS idx_brazil_nfe_branch;
DROP INDEX IF EXISTS idx_brazil_nfse_branch;
DROP INDEX IF EXISTS idx_brazil_cte_branch;
DROP INDEX IF EXISTS idx_brazil_sped_branch;
DROP INDEX IF EXISTS idx_vision_analysis_branch;
DROP INDEX IF EXISTS idx_erp_financial_branch;
DROP INDEX IF EXISTS idx_erp_inventory_branch;
DROP INDEX IF EXISTS idx_erp_procurement_branch;
DROP INDEX IF EXISTS idx_integrations_connectors_branch;
DROP INDEX IF EXISTS idx_integrations_etl_jobs_branch;
DROP INDEX IF EXISTS idx_sales_deals_branch;
DROP INDEX IF EXISTS idx_sales_contacts_branch;
DROP INDEX IF EXISTS idx_sales_activities_branch;
DROP INDEX IF EXISTS idx_minutes_meetings_branch;
DROP INDEX IF EXISTS idx_minutes_transcripts_branch;
DROP INDEX IF EXISTS idx_minutes_documents_branch;
DROP INDEX IF EXISTS idx_app_templates_branch;
DROP INDEX IF EXISTS idx_app_template_deploys_branch;
DROP INDEX IF EXISTS idx_itsm_incidents_branch;
DROP INDEX IF EXISTS idx_itsm_service_requests_branch;
DROP INDEX IF EXISTS idx_itsm_cmdb_branch;
DROP INDEX IF EXISTS idx_itsm_kb_branch;
DROP INDEX IF EXISTS idx_pos_products_branch;
DROP INDEX IF EXISTS idx_pos_orders_branch;
DROP INDEX IF EXISTS idx_handoff_queue_branch;
DROP INDEX IF EXISTS idx_conversation_analytics_branch;
DROP INDEX IF EXISTS idx_handoff_channels_branch;
DROP INDEX IF EXISTS idx_conversation_ratings_branch;
DROP INDEX IF EXISTS idx_identity_kyc_workflows_branch;
DROP INDEX IF EXISTS idx_identity_signatures_branch;
DROP INDEX IF EXISTS idx_identity_certificates_branch;
DROP INDEX IF EXISTS idx_timeclock_events_branch;
DROP INDEX IF EXISTS idx_timeclock_records_branch;
DROP INDEX IF EXISTS idx_timeclock_overtime_branch;
DROP INDEX IF EXISTS idx_timeclock_reports_branch;
DROP INDEX IF EXISTS idx_banking_transactions_branch;
DROP INDEX IF EXISTS idx_banking_platforms_branch;
DROP INDEX IF EXISTS idx_banking_reconcile_results_branch;
DROP INDEX IF EXISTS idx_banking_reports_branch;
DROP INDEX IF EXISTS idx_gl_accounts_branch;
DROP INDEX IF EXISTS idx_gl_journal_entries_branch;
DROP INDEX IF EXISTS idx_gl_journal_lines_branch;
DROP INDEX IF EXISTS idx_inventory_items_branch;
DROP INDEX IF EXISTS idx_purchase_orders_branch;
DROP INDEX IF EXISTS idx_purchase_order_items_branch;
DROP INDEX IF EXISTS idx_m365_sharepoint_items_branch;
DROP INDEX IF EXISTS idx_m365_calendar_events_branch;
DROP INDEX IF EXISTS idx_m365_onedrive_files_branch;
DROP INDEX IF EXISTS idx_oauth_microsoft_settings_branch;
DROP INDEX IF EXISTS idx_research_searches_branch;

ALTER TABLE IF EXISTS hr_employees       DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS hr_recruitment     DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS hr_attendance      DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS hr_review_cycles   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS hr_goals           DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS brazil_nfe         DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS brazil_nfse        DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS brazil_cte         DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS brazil_sped        DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS vision_analysis    DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS erp_financial      DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS erp_inventory      DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS erp_procurement    DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS erp_branches       DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS integrations_connectors DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS integrations_etl_jobs   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS sales_deals        DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS sales_contacts     DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS sales_activities   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS minutes_meetings   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS minutes_transcripts DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS minutes_documents  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS app_templates      DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS app_template_deploys DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS itsm_incidents         DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS itsm_service_requests  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS itsm_cmdb              DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS itsm_kb                DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS pos_products       DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS pos_orders         DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS handoff_queue          DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS conversation_analytics DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS handoff_channels       DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS conversation_ratings   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS identity_kyc_workflows DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS identity_signatures    DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS identity_certificates  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS timeclock_events   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS timeclock_records  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS timeclock_overtime DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS timeclock_reports  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS banking_transactions       DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS banking_platforms           DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS banking_reconcile_results   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS banking_reports             DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS gl_accounts         DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS gl_journal_entries  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS gl_journal_lines    DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS inventory_items     DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS purchase_orders     DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS purchase_order_items DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS m365_sharepoint_items DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS m365_calendar_events  DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS m365_onedrive_files   DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS oauth_microsoft_settings DROP COLUMN IF EXISTS branch_id;
ALTER TABLE IF EXISTS research_searches DROP COLUMN IF EXISTS branch_id;