use super::super::actions::{
    BOOKMARK_ACTIONS, FILE_ACTIONS, HEALTH_ACTIONS, MEDIA_ACTIONS, NEWS_ACTIONS, SMART_HOME_ACTIONS,
};
use super::super::auth::{API_KEY, GOOGLE_OAUTH2, OAUTH2, TOKEN, UNSUPPORTED};
use super::super::types::{Category, Priority, ProviderSeed, Status, Strategy};
use super::provider;

pub(super) const PROVIDERS: &[ProviderSeed] = &[
    provider(
        "google_photos",
        "Google Photos",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://developers.google.com/photos"),
        &GOOGLE_OAUTH2,
        FILE_ACTIONS,
    ),
    provider(
        "readwise",
        "Readwise",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://readwise.io/api_deets"),
        &TOKEN,
        BOOKMARK_ACTIONS,
    ),
    provider(
        "fitbit",
        "Fitbit",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://dev.fitbit.com/build/reference/web-api/"),
        &OAUTH2,
        HEALTH_ACTIONS,
    ),
    provider(
        "philips_hue",
        "Philips Hue",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://developers.meethue.com/develop/hue-api-v2/"),
        &API_KEY,
        SMART_HOME_ACTIONS,
    ),
    provider(
        "newscatcher",
        "NewsCatcher",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://www.newscatcherapi.com/docs/v3/api-reference/overview"),
        &API_KEY,
        NEWS_ACTIONS,
    ),
    provider(
        "eight_sleep",
        "Eight Sleep",
        Category::Lifestyle,
        Strategy::Verify,
        Status::Unsupported,
        Priority::Nice,
        None,
        None,
        &UNSUPPORTED,
        HEALTH_ACTIONS,
    ),
    provider(
        "last_fm",
        "Last.fm",
        Category::Lifestyle,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://www.last.fm/api"),
        &API_KEY,
        MEDIA_ACTIONS,
    ),
];
