use super::super::actions::{
    ANALYTICS_ACTIONS, CALENDAR_ACTIONS, CONTENT_ACTIONS, MARKETING_ACTIONS, MESSAGING_ACTIONS,
    SOCIAL_ACTIONS,
};
use super::super::auth::{
    API_KEY, GOOGLE_OAUTH2, INSTAGRAM_OAUTH2, OAUTH2, TELEGRAM, TOKEN, UNKNOWN, UNSUPPORTED,
    WHATSAPP,
};
use super::super::types::{Category, Priority, ProviderSeed, Status, Strategy};
use super::provider;

pub(super) const PROVIDERS: &[ProviderSeed] = &[
    // #1424/#1427 — Telegram and WhatsApp are live channel adapters
    // (`bottelegram`/`botwhatsapp`): the seeds give them the same vault-backed
    // credential setter as every other provider (Sources UI + chat), so the
    // channel secrets (bot token, webhook secret, access token, verify
    // token, phone number id) are settable without config.csv.
    provider(
        "telegram",
        "Telegram",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Must,
        Some("bottelegram"),
        Some("https://core.telegram.org/bots/api"),
        &TELEGRAM,
        MESSAGING_ACTIONS,
    ),
    provider(
        "whatsapp",
        "WhatsApp Business",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Must,
        Some("botwhatsapp"),
        Some("https://developers.facebook.com/docs/whatsapp/cloud-api"),
        &WHATSAPP,
        MESSAGING_ACTIONS,
    ),
    // Instagram is a live adapter (`botintegrations::providers::instagram`),
    // so the seed flips llm_available while `action_is_implemented` keeps the
    // per-action truth in sync with the registered adapter. Status stays
    // Partial because the Graph API exposes no media search and no media
    // delete for Instagram, so only list/get/publish execute today.
    ProviderSeed {
        llm_available: true,
        ..provider(
            "instagram",
            "Instagram",
            Category::SocialMessaging,
            Strategy::Integrate,
            Status::Partial,
            Priority::Must,
            Some("botinstagram"),
            Some("https://developers.facebook.com/docs/instagram-platform"),
            &INSTAGRAM_OAUTH2,
            SOCIAL_ACTIONS,
        )
    },
    provider(
        "facebook_pages",
        "Facebook Pages",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Must,
        Some("botsocial"),
        Some("https://developers.facebook.com/docs/pages-api/"),
        &OAUTH2,
        SOCIAL_ACTIONS,
    ),
    provider(
        "pinterest",
        "Pinterest",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://developers.pinterest.com/docs/api/v5/"),
        &OAUTH2,
        SOCIAL_ACTIONS,
    ),
    provider(
        "reddit",
        "Reddit",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://www.reddit.com/dev/api/"),
        &OAUTH2,
        SOCIAL_ACTIONS,
    ),
    provider(
        "twitch",
        "Twitch",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://dev.twitch.tv/docs/api/"),
        &OAUTH2,
        SOCIAL_ACTIONS,
    ),
    provider(
        "bluesky",
        "Bluesky",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://docs.bsky.app/docs/api/at-protocol-xrpc-api"),
        &TOKEN,
        SOCIAL_ACTIONS,
    ),
    provider(
        "mastodon",
        "Mastodon",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://docs.joinmastodon.org/api/"),
        &OAUTH2,
        SOCIAL_ACTIONS,
    ),
    provider(
        "signal",
        "Signal",
        Category::SocialMessaging,
        Strategy::Verify,
        Status::Unsupported,
        Priority::Nice,
        None,
        None,
        &UNSUPPORTED,
        MESSAGING_ACTIONS,
    ),
    provider(
        "youtube_analytics",
        "YouTube Analytics",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Unsupported,
        Priority::Nice,
        None,
        Some("https://developers.google.com/youtube/analytics"),
        &GOOGLE_OAUTH2,
        ANALYTICS_ACTIONS,
    ),
    provider(
        "linkedin_ads",
        "LinkedIn Ads",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Unsupported,
        Priority::Nice,
        None,
        Some("https://learn.microsoft.com/linkedin/marketing/"),
        &OAUTH2,
        MARKETING_ACTIONS,
    ),
    provider(
        "luma",
        "Luma",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        None,
        &API_KEY,
        CALENDAR_ACTIONS,
    ),
    provider(
        "blogger",
        "Blogger",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://developers.google.com/blogger/docs/3.0/getting_started"),
        &GOOGLE_OAUTH2,
        CONTENT_ACTIONS,
    ),
    provider(
        "beehiiv",
        "Beehiiv",
        Category::SocialMessaging,
        Strategy::Integrate,
        Status::Built,
        Priority::Nice,
        None,
        Some("https://developers.beehiiv.com/api-reference"),
        &API_KEY,
        CONTENT_ACTIONS,
    ),
    provider(
        "moltbook",
        "Moltbook",
        Category::SocialMessaging,
        Strategy::Verify,
        Status::Built,
        Priority::Nice,
        None,
        None,
        &UNKNOWN,
        CONTENT_ACTIONS,
    ),
];
