[package]
name = "botsettings"
version.workspace = true
edition = "2021"

[features]
default = []
rbac = []
mail = ["dep:lettre"]

[dependencies]
botcore = { path = "../botcore" }
botsecurity = { path = "../botsecurity" }
botcoredirectory = { path = "../botcoredirectory" }
botcoreoauth = { path = "../botcoreoauth" }
botcoresecrets = { path = "../botcoresecrets" }
botschema = { path = "../../../botschema" }
axum = { workspace = true, features = ["ws", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
diesel = { workspace = true, features = ["postgres", "r2d2", "chrono", "serde_json", "uuid"] }
chrono = { workspace = true, features = ["clock", "std"] }
uuid = { workspace = true, features = ["v4", "v5", "serde"] }
log = { workspace = true }
anyhow = { workspace = true }
lettre = { workspace = true, optional = true }
tracing = { workspace = true }
redis = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
bigdecimal = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls", "json"] }

[lints]
workspace = true
