use super::Permission;

impl Permission {
    pub(crate) fn from_alias_chunk1(s_lower: &str) -> Option<Self> {
    if s_lower == "read" { return Some(Self::Read); }
    if s_lower == "write" { return Some(Self::Write); }
    if s_lower == "delete" { return Some(Self::Delete); }
    if s_lower == "admin" { return Some(Self::Admin); }
    if s_lower == "admin:manage:users" { return Some(Self::ManageUsers); }
    if s_lower == "bot:manage:*" { return Some(Self::ManageBots); }
    if s_lower == "analytics:view:*" { return Some(Self::ViewAnalytics); }
    if s_lower == "admin:manage:settings" { return Some(Self::ManageSettings); }
    if s_lower == "tasks:execute:*" { return Some(Self::ExecuteTasks); }
    if s_lower == "security:view:logs" { return Some(Self::ViewLogs); }
    if s_lower == "security:manage:secrets" { return Some(Self::ManageSecrets); }
    if s_lower == "api:access:*" { return Some(Self::AccessApi); }
    if s_lower == "drive:manage:*" { return Some(Self::ManageFiles); }
    if s_lower == "chat:send:messages" { return Some(Self::SendMessages); }
    if s_lower == "chat:view:conversations" { return Some(Self::ViewConversations); }
    if s_lower == "integrations:manage:webhooks" { return Some(Self::ManageWebhooks); }
    if s_lower == "integrations:manage:*" { return Some(Self::ManageIntegrations); }
    if s_lower == "admin:manage:organization" { return Some(Self::AdministrationCanManageOrganization); }
    if s_lower == "admin.manage.organization" { return Some(Self::AdministrationCanManageOrganization); }
    if s_lower == "admin:manage:members" { return Some(Self::AdministrationCanManageMembers); }
    if s_lower == "admin.manage.members" { return Some(Self::AdministrationCanManageMembers); }
    if s_lower == "admin:view:members" { return Some(Self::AdministrationCanViewMembers); }
    if s_lower == "admin.view.members" { return Some(Self::AdministrationCanViewMembers); }
    if s_lower == "admin.manage.settings" { return Some(Self::AdministrationCanManageSettings); }
    if s_lower == "admin:manage:billing" { return Some(Self::AdministrationCanManageBilling); }
    if s_lower == "admin.manage.billing" { return Some(Self::AdministrationCanManageBilling); }
    if s_lower == "admin:view:billing" { return Some(Self::AdministrationCanViewBilling); }
    if s_lower == "admin.view.billing" { return Some(Self::AdministrationCanViewBilling); }
    if s_lower == "admin:manage:auditlog" { return Some(Self::AdministrationCanManageAuditLog); }
    if s_lower == "admin.manage.auditlog" { return Some(Self::AdministrationCanManageAuditLog); }
    if s_lower == "admin:view:auditlog" { return Some(Self::AdministrationCanViewAuditLog); }
    if s_lower == "admin.view.auditlog" { return Some(Self::AdministrationCanViewAuditLog); }
    if s_lower == "admin:manage:dns" { return Some(Self::AdministrationCanManageDns); }
    if s_lower == "admin.manage.dns" { return Some(Self::AdministrationCanManageDns); }
    if s_lower == "admin:manage:onboarding" { return Some(Self::AdministrationCanManageOnboarding); }
    if s_lower == "admin.manage.onboarding" { return Some(Self::AdministrationCanManageOnboarding); }
    if s_lower == "admin:manage:roles" { return Some(Self::AdministrationCanManageRoles); }
    if s_lower == "admin.manage.roles" { return Some(Self::AdministrationCanManageRoles); }
    if s_lower == "admin:manage:groups" { return Some(Self::AdministrationCanManageGroups); }
    if s_lower == "admin.manage.groups" { return Some(Self::AdministrationCanManageGroups); }
    if s_lower == "compliance:view:dashboard" { return Some(Self::ComplianceCanViewDashboard); }
    if s_lower == "compliance.view.dashboard" { return Some(Self::ComplianceCanViewDashboard); }
    if s_lower == "compliance:manage:policies" { return Some(Self::ComplianceCanManagePolicies); }
    if s_lower == "compliance.manage.policies" { return Some(Self::ComplianceCanManagePolicies); }
    if s_lower == "compliance:view:reports" { return Some(Self::ComplianceCanViewReports); }
    if s_lower == "compliance.view.reports" { return Some(Self::ComplianceCanViewReports); }
    if s_lower == "compliance:export:reports" { return Some(Self::ComplianceCanExportReports); }
    if s_lower == "compliance.export.reports" { return Some(Self::ComplianceCanExportReports); }
    if s_lower == "compliance:manage:dataretention" { return Some(Self::ComplianceCanManageDataRetention); }
    if s_lower == "compliance.manage.dataretention" { return Some(Self::ComplianceCanManageDataRetention); }
    if s_lower == "compliance:manage:gdpr" { return Some(Self::ComplianceCanManageGdpr); }
    if s_lower == "compliance.manage.gdpr" { return Some(Self::ComplianceCanManageGdpr); }
    if s_lower == "compliance:manage:hipaa" { return Some(Self::ComplianceCanManageHipaa); }
    if s_lower == "compliance.manage.hipaa" { return Some(Self::ComplianceCanManageHipaa); }
    if s_lower == "compliance:manage:iso27001" { return Some(Self::ComplianceCanManageIso27001); }
    if s_lower == "compliance.manage.iso27001" { return Some(Self::ComplianceCanManageIso27001); }
    if s_lower == "compliance:manage:soc2" { return Some(Self::ComplianceCanManageSoc2); }
    if s_lower == "compliance.manage.soc2" { return Some(Self::ComplianceCanManageSoc2); }
    if s_lower == "security:manage:users" { return Some(Self::SecurityCanManageUsers); }
    if s_lower == "security.manage.users" { return Some(Self::SecurityCanManageUsers); }
    if s_lower == "security.manage.secrets" { return Some(Self::SecurityCanManageSecrets); }
    if s_lower == "security.view.logs" { return Some(Self::SecurityCanViewLogs); }
    if s_lower == "security:manage:apikeys" { return Some(Self::SecurityCanManageApiKeys); }
    if s_lower == "security.manage.apikeys" { return Some(Self::SecurityCanManageApiKeys); }
    if s_lower == "security:manage:ipsafelist" { return Some(Self::SecurityCanManageIpSafelist); }
    if s_lower == "security.manage.ipsafelist" { return Some(Self::SecurityCanManageIpSafelist); }
    if s_lower == "security:manage:mfa" { return Some(Self::SecurityCanManageMfa); }
    if s_lower == "security.manage.mfa" { return Some(Self::SecurityCanManageMfa); }
    if s_lower == "security:manage:sessions" { return Some(Self::SecurityCanManageSessions); }
    if s_lower == "security.manage.sessions" { return Some(Self::SecurityCanManageSessions); }
    if s_lower == "security:manage:encryption" { return Some(Self::SecurityCanManageEncryption); }
    if s_lower == "security.manage.encryption" { return Some(Self::SecurityCanManageEncryption); }
    if s_lower == "security:manage:integrations" { return Some(Self::SecurityCanManageIntegrations); }
    if s_lower == "security.manage.integrations" { return Some(Self::SecurityCanManageIntegrations); }
    if s_lower == "security:manage:passwordpolicy" { return Some(Self::SecurityCanManagePasswordPolicy); }
    if s_lower == "security.manage.passwordpolicy" { return Some(Self::SecurityCanManagePasswordPolicy); }
    if s_lower == "security:configure:*" { return Some(Self::SecurityCanConfigure); }
    if s_lower == "security.configure.*" { return Some(Self::SecurityCanConfigure); }
    if s_lower == "security:admin:*" { return Some(Self::SecurityCanAdmin); }
    if s_lower == "security.admin.*" { return Some(Self::SecurityCanAdmin); }
    if s_lower == "mail:read:*" { return Some(Self::MailCanRead); }
    if s_lower == "mail.read.*" { return Some(Self::MailCanRead); }
    if s_lower == "mail:send:*" { return Some(Self::MailCanSend); }
    if s_lower == "mail.send.*" { return Some(Self::MailCanSend); }
    if s_lower == "mail:delete:*" { return Some(Self::MailCanDelete); }
    if s_lower == "mail.delete.*" { return Some(Self::MailCanDelete); }
    if s_lower == "mail:manage:folders" { return Some(Self::MailCanManageFolders); }
    if s_lower == "mail.manage.folders" { return Some(Self::MailCanManageFolders); }
    if s_lower == "mail:manage:filters" { return Some(Self::MailCanManageFilters); }
    if s_lower == "mail.manage.filters" { return Some(Self::MailCanManageFilters); }
    if s_lower == "mail:manage:templates" { return Some(Self::MailCanManageTemplates); }
    if s_lower == "mail.manage.templates" { return Some(Self::MailCanManageTemplates); }
    if s_lower == "mail:manage:signatures" { return Some(Self::MailCanManageSignatures); }
    if s_lower == "mail.manage.signatures" { return Some(Self::MailCanManageSignatures); }
    if s_lower == "mail:manage:autoreply" { return Some(Self::MailCanManageAutoReply); }
    if s_lower == "mail.manage.autoreply" { return Some(Self::MailCanManageAutoReply); }
    if s_lower == "mail:manage:forwarding" { return Some(Self::MailCanManageForwarding); }
    if s_lower == "mail.manage.forwarding" { return Some(Self::MailCanManageForwarding); }
    if s_lower == "mail:send:campaigns" { return Some(Self::MailCanSendCampaigns); }
    if s_lower == "mail.send.campaigns" { return Some(Self::MailCanSendCampaigns); }
    if s_lower == "mail:admin:*" { return Some(Self::MailCanAdmin); }
    if s_lower == "mail.admin.*" { return Some(Self::MailCanAdmin); }
    if s_lower == "mail:configure:*" { return Some(Self::MailCanConfigure); }
    if s_lower == "mail.configure.*" { return Some(Self::MailCanConfigure); }
    if s_lower == "calendar:read:*" { return Some(Self::CalendarCanRead); }
    if s_lower == "calendar.read.*" { return Some(Self::CalendarCanRead); }
    if s_lower == "calendar:create:*" { return Some(Self::CalendarCanCreate); }
    if s_lower == "calendar.create.*" { return Some(Self::CalendarCanCreate); }
    if s_lower == "calendar:update:*" { return Some(Self::CalendarCanUpdate); }
    if s_lower == "calendar.update.*" { return Some(Self::CalendarCanUpdate); }
    if s_lower == "calendar:delete:*" { return Some(Self::CalendarCanDelete); }
    if s_lower == "calendar.delete.*" { return Some(Self::CalendarCanDelete); }
    if s_lower == "calendar:manage:calendars" { return Some(Self::CalendarCanManageCalendars); }
    if s_lower == "calendar.manage.calendars" { return Some(Self::CalendarCanManageCalendars); }
    if s_lower == "calendar:share:*" { return Some(Self::CalendarCanShare); }
    if s_lower == "calendar.share.*" { return Some(Self::CalendarCanShare); }
    if s_lower == "calendar:manage:reminders" { return Some(Self::CalendarCanManageReminders); }
    if s_lower == "calendar.manage.reminders" { return Some(Self::CalendarCanManageReminders); }
    if s_lower == "calendar:view:availability" { return Some(Self::CalendarCanViewAvailability); }
    if s_lower == "calendar.view.availability" { return Some(Self::CalendarCanViewAvailability); }
    if s_lower == "drive:read:*" { return Some(Self::DriveCanRead); }
    if s_lower == "drive.read.*" { return Some(Self::DriveCanRead); }
    if s_lower == "drive:write:*" { return Some(Self::DriveCanWrite); }
    if s_lower == "drive.write.*" { return Some(Self::DriveCanWrite); }
    if s_lower == "drive:delete:*" { return Some(Self::DriveCanDelete); }
    if s_lower == "drive.delete.*" { return Some(Self::DriveCanDelete); }
    if s_lower == "drive:upload:*" { return Some(Self::DriveCanUpload); }
    if s_lower == "drive.upload.*" { return Some(Self::DriveCanUpload); }
    if s_lower == "drive:download:*" { return Some(Self::DriveCanDownload); }
    if s_lower == "drive.download.*" { return Some(Self::DriveCanDownload); }
    if s_lower == "drive:manage:folders" { return Some(Self::DriveCanManageFolders); }
    if s_lower == "drive.manage.folders" { return Some(Self::DriveCanManageFolders); }
    if s_lower == "drive:share:*" { return Some(Self::DriveCanShare); }
    if s_lower == "drive.share.*" { return Some(Self::DriveCanShare); }
    if s_lower == "drive:manage:permissions" { return Some(Self::DriveCanManagePermissions); }
    if s_lower == "drive.manage.permissions" { return Some(Self::DriveCanManagePermissions); }
    if s_lower == "drive:admin:*" { return Some(Self::DriveCanAdmin); }
    if s_lower == "drive.admin.*" { return Some(Self::DriveCanAdmin); }
    if s_lower == "drive:manage:versions" { return Some(Self::DriveCanManageVersions); }
    if s_lower == "drive.manage.versions" { return Some(Self::DriveCanManageVersions); }
    None
    }
}

