use super::Permission;

impl Permission {
    pub(crate) fn from_alias_chunk2(s_lower: &str) -> Option<Self> {
    if s_lower == "documents:read:*" { return Some(Self::DocumentsCanRead); }
    if s_lower == "documents.read.*" { return Some(Self::DocumentsCanRead); }
    if s_lower == "documents:create:*" { return Some(Self::DocumentsCanCreate); }
    if s_lower == "documents.create.*" { return Some(Self::DocumentsCanCreate); }
    if s_lower == "documents:update:*" { return Some(Self::DocumentsCanUpdate); }
    if s_lower == "documents.update.*" { return Some(Self::DocumentsCanUpdate); }
    if s_lower == "documents:delete:*" { return Some(Self::DocumentsCanDelete); }
    if s_lower == "documents.delete.*" { return Some(Self::DocumentsCanDelete); }
    if s_lower == "documents:share:*" { return Some(Self::DocumentsCanShare); }
    if s_lower == "documents.share.*" { return Some(Self::DocumentsCanShare); }
    if s_lower == "documents:export:*" { return Some(Self::DocumentsCanExport); }
    if s_lower == "documents.export.*" { return Some(Self::DocumentsCanExport); }
    if s_lower == "documents:manage:templates" { return Some(Self::DocumentsCanManageTemplates); }
    if s_lower == "documents.manage.templates" { return Some(Self::DocumentsCanManageTemplates); }
    if s_lower == "documents:manage:folders" { return Some(Self::DocumentsCanManageFolders); }
    if s_lower == "documents.manage.folders" { return Some(Self::DocumentsCanManageFolders); }
    if s_lower == "documents:comment:*" { return Some(Self::DocumentsCanComment); }
    if s_lower == "documents.comment.*" { return Some(Self::DocumentsCanComment); }
    if s_lower == "documents:track:changes" { return Some(Self::DocumentsCanTrackChanges); }
    if s_lower == "documents.track.changes" { return Some(Self::DocumentsCanTrackChanges); }
    if s_lower == "spreadsheets:read:*" { return Some(Self::SpreadsheetsCanRead); }
    if s_lower == "spreadsheets.read.*" { return Some(Self::SpreadsheetsCanRead); }
    if s_lower == "spreadsheets:create:*" { return Some(Self::SpreadsheetsCanCreate); }
    if s_lower == "spreadsheets.create.*" { return Some(Self::SpreadsheetsCanCreate); }
    if s_lower == "spreadsheets:update:*" { return Some(Self::SpreadsheetsCanUpdate); }
    if s_lower == "spreadsheets.update.*" { return Some(Self::SpreadsheetsCanUpdate); }
    if s_lower == "spreadsheets:delete:*" { return Some(Self::SpreadsheetsCanDelete); }
    if s_lower == "spreadsheets.delete.*" { return Some(Self::SpreadsheetsCanDelete); }
    if s_lower == "spreadsheets:share:*" { return Some(Self::SpreadsheetsCanShare); }
    if s_lower == "spreadsheets.share.*" { return Some(Self::SpreadsheetsCanShare); }
    if s_lower == "spreadsheets:export:*" { return Some(Self::SpreadsheetsCanExport); }
    if s_lower == "spreadsheets.export.*" { return Some(Self::SpreadsheetsCanExport); }
    if s_lower == "spreadsheets:import:*" { return Some(Self::SpreadsheetsCanImport); }
    if s_lower == "spreadsheets.import.*" { return Some(Self::SpreadsheetsCanImport); }
    if s_lower == "spreadsheets:manage:formulas" { return Some(Self::SpreadsheetsCanManageFormulas); }
    if s_lower == "spreadsheets.manage.formulas" { return Some(Self::SpreadsheetsCanManageFormulas); }
    if s_lower == "spreadsheets:manage:charts" { return Some(Self::SpreadsheetsCanManageCharts); }
    if s_lower == "spreadsheets.manage.charts" { return Some(Self::SpreadsheetsCanManageCharts); }
    if s_lower == "presentations:read:*" { return Some(Self::PresentationsCanRead); }
    if s_lower == "presentations.read.*" { return Some(Self::PresentationsCanRead); }
    if s_lower == "presentations:create:*" { return Some(Self::PresentationsCanCreate); }
    if s_lower == "presentations.create.*" { return Some(Self::PresentationsCanCreate); }
    if s_lower == "presentations:update:*" { return Some(Self::PresentationsCanUpdate); }
    if s_lower == "presentations.update.*" { return Some(Self::PresentationsCanUpdate); }
    if s_lower == "presentations:delete:*" { return Some(Self::PresentationsCanDelete); }
    if s_lower == "presentations.delete.*" { return Some(Self::PresentationsCanDelete); }
    if s_lower == "presentations:present:*" { return Some(Self::PresentationsCanPresent); }
    if s_lower == "presentations.present.*" { return Some(Self::PresentationsCanPresent); }
    if s_lower == "presentations:export:*" { return Some(Self::PresentationsCanExport); }
    if s_lower == "presentations.export.*" { return Some(Self::PresentationsCanExport); }
    if s_lower == "meetings:create:*" { return Some(Self::MeetingsCanCreate); }
    if s_lower == "meetings.create.*" { return Some(Self::MeetingsCanCreate); }
    if s_lower == "meetings:join:*" { return Some(Self::MeetingsCanJoin); }
    if s_lower == "meetings.join.*" { return Some(Self::MeetingsCanJoin); }
    if s_lower == "meetings:manage:rooms" { return Some(Self::MeetingsCanManageRooms); }
    if s_lower == "meetings.manage.rooms" { return Some(Self::MeetingsCanManageRooms); }
    if s_lower == "meetings:record:*" { return Some(Self::MeetingsCanRecord); }
    if s_lower == "meetings.record.*" { return Some(Self::MeetingsCanRecord); }
    if s_lower == "meetings:share:screen" { return Some(Self::MeetingsCanShareScreen); }
    if s_lower == "meetings.share.screen" { return Some(Self::MeetingsCanShareScreen); }
    if s_lower == "meetings:manage:participants" { return Some(Self::MeetingsCanManageParticipants); }
    if s_lower == "meetings.manage.participants" { return Some(Self::MeetingsCanManageParticipants); }
    if s_lower == "meetings:manage:settings" { return Some(Self::MeetingsCanManageSettings); }
    if s_lower == "meetings.manage.settings" { return Some(Self::MeetingsCanManageSettings); }
    if s_lower == "meetings:admin:*" { return Some(Self::MeetingsCanAdmin); }
    if s_lower == "meetings.admin.*" { return Some(Self::MeetingsCanAdmin); }
    if s_lower == "chat.send.messages" { return Some(Self::ChatCanSendMessages); }
    if s_lower == "chat:read:messages" { return Some(Self::ChatCanReadMessages); }
    if s_lower == "chat.read.messages" { return Some(Self::ChatCanReadMessages); }
    if s_lower == "chat:delete:messages" { return Some(Self::ChatCanDeleteMessages); }
    if s_lower == "chat.delete.messages" { return Some(Self::ChatCanDeleteMessages); }
    if s_lower == "chat.view.conversations" { return Some(Self::ChatCanViewConversations); }
    if s_lower == "chat:manage:bots" { return Some(Self::ChatCanManageBots); }
    if s_lower == "chat.manage.bots" { return Some(Self::ChatCanManageBots); }
    if s_lower == "chat:create:bots" { return Some(Self::ChatCanCreateBots); }
    if s_lower == "chat.create.bots" { return Some(Self::ChatCanCreateBots); }
    if s_lower == "chat:edit:bots" { return Some(Self::ChatCanEditBots); }
    if s_lower == "chat.edit.bots" { return Some(Self::ChatCanEditBots); }
    if s_lower == "chat:delete:bots" { return Some(Self::ChatCanDeleteBots); }
    if s_lower == "chat.delete.bots" { return Some(Self::ChatCanDeleteBots); }
    if s_lower == "chat:publish:bots" { return Some(Self::ChatCanPublishBots); }
    if s_lower == "chat.publish.bots" { return Some(Self::ChatCanPublishBots); }
    if s_lower == "chat:view:bots" { return Some(Self::ChatCanViewBots); }
    if s_lower == "chat.view.bots" { return Some(Self::ChatCanViewBots); }
    if s_lower == "chat:execute:tools" { return Some(Self::ChatCanExecuteTools); }
    if s_lower == "chat.execute.tools" { return Some(Self::ChatCanExecuteTools); }
    if s_lower == "chat:manage:knowledgebase" { return Some(Self::ChatCanManageKnowledgeBase); }
    if s_lower == "chat.manage.knowledgebase" { return Some(Self::ChatCanManageKnowledgeBase); }
    if s_lower == "chat:read:knowledgebase" { return Some(Self::ChatCanReadKnowledgeBase); }
    if s_lower == "chat.read.knowledgebase" { return Some(Self::ChatCanReadKnowledgeBase); }
    if s_lower == "chat:write:knowledgebase" { return Some(Self::ChatCanWriteKnowledgeBase); }
    if s_lower == "chat.write.knowledgebase" { return Some(Self::ChatCanWriteKnowledgeBase); }
    if s_lower == "chat:admin:knowledgebase" { return Some(Self::ChatCanAdminKnowledgeBase); }
    if s_lower == "chat.admin.knowledgebase" { return Some(Self::ChatCanAdminKnowledgeBase); }
    if s_lower == "chat:configure:bots" { return Some(Self::ChatCanConfigureBots); }
    if s_lower == "chat.configure.bots" { return Some(Self::ChatCanConfigureBots); }
    if s_lower == "tasks:create:*" { return Some(Self::TasksCanCreate); }
    if s_lower == "tasks.create.*" { return Some(Self::TasksCanCreate); }
    if s_lower == "tasks:read:*" { return Some(Self::TasksCanRead); }
    if s_lower == "tasks.read.*" { return Some(Self::TasksCanRead); }
    if s_lower == "tasks:update:*" { return Some(Self::TasksCanUpdate); }
    if s_lower == "tasks.update.*" { return Some(Self::TasksCanUpdate); }
    if s_lower == "tasks:delete:*" { return Some(Self::TasksCanDelete); }
    if s_lower == "tasks.delete.*" { return Some(Self::TasksCanDelete); }
    if s_lower == "tasks.execute.*" { return Some(Self::TasksCanExecute); }
    if s_lower == "tasks:assign:*" { return Some(Self::TasksCanAssign); }
    if s_lower == "tasks.assign.*" { return Some(Self::TasksCanAssign); }
    if s_lower == "tasks:manage:projects" { return Some(Self::TasksCanManageProjects); }
    if s_lower == "tasks.manage.projects" { return Some(Self::TasksCanManageProjects); }
    if s_lower == "tasks:manage:workflows" { return Some(Self::TasksCanManageWorkflows); }
    if s_lower == "tasks.manage.workflows" { return Some(Self::TasksCanManageWorkflows); }
    if s_lower == "tasks:manage:autotask" { return Some(Self::TasksCanManageAutoTask); }
    if s_lower == "tasks.manage.autotask" { return Some(Self::TasksCanManageAutoTask); }
    if s_lower == "aitools:manage:llm" { return Some(Self::AiToolsCanManageLlm); }
    if s_lower == "aitools.manage.llm" { return Some(Self::AiToolsCanManageLlm); }
    if s_lower == "aitools:configure:llm" { return Some(Self::AiToolsCanConfigureLlm); }
    if s_lower == "aitools.configure.llm" { return Some(Self::AiToolsCanConfigureLlm); }
    if s_lower == "aitools:manage:models" { return Some(Self::AiToolsCanManageModels); }
    if s_lower == "aitools.manage.models" { return Some(Self::AiToolsCanManageModels); }
    if s_lower == "aitools:manage:prompts" { return Some(Self::AiToolsCanManagePrompts); }
    if s_lower == "aitools.manage.prompts" { return Some(Self::AiToolsCanManagePrompts); }
    if s_lower == "aitools:design:scripts" { return Some(Self::AiToolsCanDesignScripts); }
    if s_lower == "aitools.design.scripts" { return Some(Self::AiToolsCanDesignScripts); }
    if s_lower == "aitools:edit:scripts" { return Some(Self::AiToolsCanEditScripts); }
    if s_lower == "aitools.edit.scripts" { return Some(Self::AiToolsCanEditScripts); }
    if s_lower == "aitools:manage:autotask" { return Some(Self::AiToolsCanManageAutotask); }
    if s_lower == "aitools.manage.autotask" { return Some(Self::AiToolsCanManageAutotask); }
    if s_lower == "aitools:manage:training" { return Some(Self::AiToolsCanManageTraining); }
    if s_lower == "aitools.manage.training" { return Some(Self::AiToolsCanManageTraining); }
    if s_lower == "aitools:manage:vibe" { return Some(Self::AiToolsCanManageVibe); }
    if s_lower == "aitools.manage.vibe" { return Some(Self::AiToolsCanManageVibe); }
    if s_lower == "aitools:manage:mcp" { return Some(Self::AiToolsCanManageMcp); }
    if s_lower == "aitools.manage.mcp" { return Some(Self::AiToolsCanManageMcp); }
    if s_lower == "analytics:view:dashboard" { return Some(Self::BusinessIntelligenceCanViewDashboard); }
    if s_lower == "analytics.view.dashboard" { return Some(Self::BusinessIntelligenceCanViewDashboard); }
    if s_lower == "analytics:view:reports" { return Some(Self::BusinessIntelligenceCanViewReports); }
    if s_lower == "analytics.view.reports" { return Some(Self::BusinessIntelligenceCanViewReports); }
    if s_lower == "analytics:create:reports" { return Some(Self::BusinessIntelligenceCanCreateReports); }
    if s_lower == "analytics.create.reports" { return Some(Self::BusinessIntelligenceCanCreateReports); }
    if s_lower == "analytics:edit:reports" { return Some(Self::BusinessIntelligenceCanEditReports); }
    if s_lower == "analytics.edit.reports" { return Some(Self::BusinessIntelligenceCanEditReports); }
    if s_lower == "analytics:delete:reports" { return Some(Self::BusinessIntelligenceCanDeleteReports); }
    if s_lower == "analytics.delete.reports" { return Some(Self::BusinessIntelligenceCanDeleteReports); }
    if s_lower == "analytics:export:reports" { return Some(Self::BusinessIntelligenceCanExportReports); }
    if s_lower == "analytics.export.reports" { return Some(Self::BusinessIntelligenceCanExportReports); }
    if s_lower == "analytics:view:metrics" { return Some(Self::BusinessIntelligenceCanViewMetrics); }
    if s_lower == "analytics.view.metrics" { return Some(Self::BusinessIntelligenceCanViewMetrics); }
    if s_lower == "analytics:manage:dashboards" { return Some(Self::BusinessIntelligenceCanManageDashboards); }
    if s_lower == "analytics.manage.dashboards" { return Some(Self::BusinessIntelligenceCanManageDashboards); }
    if s_lower == "analytics:trace:*" { return Some(Self::BusinessIntelligenceCanTrace); }
    if s_lower == "analytics.trace.*" { return Some(Self::BusinessIntelligenceCanTrace); }
    if s_lower == "analytics:monitor:performance" { return Some(Self::BusinessIntelligenceCanMonitorPerformance); }
    if s_lower == "analytics.monitor.performance" { return Some(Self::BusinessIntelligenceCanMonitorPerformance); }
    if s_lower == "analytics:view:analytics" { return Some(Self::BusinessIntelligenceCanViewAnalytics); }
    if s_lower == "analytics.view.analytics" { return Some(Self::BusinessIntelligenceCanViewAnalytics); }
    if s_lower == "analytics:export:analytics" { return Some(Self::BusinessIntelligenceCanExportAnalytics); }
    if s_lower == "analytics.export.analytics" { return Some(Self::BusinessIntelligenceCanExportAnalytics); }
    None
    }
}

