use super::Permission;

impl Permission {
    pub(crate) fn from_alias_chunk5(s_lower: &str) -> Option<Self> {
    if s_lower == "compliancecanviewdashboard" { return Some(Self::ComplianceCanViewDashboard); }
    if s_lower == "compliancecanmanagepolicies" { return Some(Self::ComplianceCanManagePolicies); }
    if s_lower == "compliancecanviewreports" { return Some(Self::ComplianceCanViewReports); }
    if s_lower == "compliancecanexportreports" { return Some(Self::ComplianceCanExportReports); }
    if s_lower == "compliancecanmanagedataretention" { return Some(Self::ComplianceCanManageDataRetention); }
    if s_lower == "compliancecanmanagegdpr" { return Some(Self::ComplianceCanManageGdpr); }
    if s_lower == "compliancecanmanagehipaa" { return Some(Self::ComplianceCanManageHipaa); }
    if s_lower == "compliancecanmanageiso27001" { return Some(Self::ComplianceCanManageIso27001); }
    if s_lower == "compliancecanmanagesoc2" { return Some(Self::ComplianceCanManageSoc2); }
    if s_lower == "securitycanmanageusers" { return Some(Self::SecurityCanManageUsers); }
    if s_lower == "securitycanmanagesecrets" { return Some(Self::SecurityCanManageSecrets); }
    if s_lower == "securitycanviewlogs" { return Some(Self::SecurityCanViewLogs); }
    if s_lower == "securitycanmanageapikeys" { return Some(Self::SecurityCanManageApiKeys); }
    if s_lower == "securitycanmanageipsafelist" { return Some(Self::SecurityCanManageIpSafelist); }
    if s_lower == "securitycanmanagemfa" { return Some(Self::SecurityCanManageMfa); }
    if s_lower == "securitycanmanagesessions" { return Some(Self::SecurityCanManageSessions); }
    if s_lower == "securitycanmanageencryption" { return Some(Self::SecurityCanManageEncryption); }
    if s_lower == "securitycanmanageintegrations" { return Some(Self::SecurityCanManageIntegrations); }
    if s_lower == "securitycanmanagepasswordpolicy" { return Some(Self::SecurityCanManagePasswordPolicy); }
    if s_lower == "securitycanconfigure" { return Some(Self::SecurityCanConfigure); }
    if s_lower == "securitycanadmin" { return Some(Self::SecurityCanAdmin); }
    if s_lower == "mailcanread" { return Some(Self::MailCanRead); }
    if s_lower == "mailcansend" { return Some(Self::MailCanSend); }
    if s_lower == "mailcandelete" { return Some(Self::MailCanDelete); }
    if s_lower == "mailcanmanagefolders" { return Some(Self::MailCanManageFolders); }
    if s_lower == "mailcanmanagefilters" { return Some(Self::MailCanManageFilters); }
    if s_lower == "mailcanmanagetemplates" { return Some(Self::MailCanManageTemplates); }
    if s_lower == "mailcanmanagesignatures" { return Some(Self::MailCanManageSignatures); }
    if s_lower == "mailcanmanageautoreply" { return Some(Self::MailCanManageAutoReply); }
    if s_lower == "mailcanmanageforwarding" { return Some(Self::MailCanManageForwarding); }
    if s_lower == "mailcansendcampaigns" { return Some(Self::MailCanSendCampaigns); }
    if s_lower == "mailcanadmin" { return Some(Self::MailCanAdmin); }
    if s_lower == "mailcanconfigure" { return Some(Self::MailCanConfigure); }
    if s_lower == "calendarcanread" { return Some(Self::CalendarCanRead); }
    if s_lower == "calendarcancreate" { return Some(Self::CalendarCanCreate); }
    if s_lower == "calendarcanupdate" { return Some(Self::CalendarCanUpdate); }
    if s_lower == "calendarcandelete" { return Some(Self::CalendarCanDelete); }
    if s_lower == "calendarcanmanagecalendars" { return Some(Self::CalendarCanManageCalendars); }
    if s_lower == "calendarcanshare" { return Some(Self::CalendarCanShare); }
    if s_lower == "calendarcanmanagereminders" { return Some(Self::CalendarCanManageReminders); }
    if s_lower == "calendarcanviewavailability" { return Some(Self::CalendarCanViewAvailability); }
    if s_lower == "drivecanread" { return Some(Self::DriveCanRead); }
    if s_lower == "drivecanwrite" { return Some(Self::DriveCanWrite); }
    if s_lower == "drivecandelete" { return Some(Self::DriveCanDelete); }
    if s_lower == "drivecanupload" { return Some(Self::DriveCanUpload); }
    if s_lower == "drivecandownload" { return Some(Self::DriveCanDownload); }
    if s_lower == "drivecanmanagefolders" { return Some(Self::DriveCanManageFolders); }
    if s_lower == "drivecanshare" { return Some(Self::DriveCanShare); }
    if s_lower == "drivecanmanagepermissions" { return Some(Self::DriveCanManagePermissions); }
    if s_lower == "drivecanadmin" { return Some(Self::DriveCanAdmin); }
    if s_lower == "drivecanmanageversions" { return Some(Self::DriveCanManageVersions); }
    if s_lower == "documentscanread" { return Some(Self::DocumentsCanRead); }
    if s_lower == "documentscancreate" { return Some(Self::DocumentsCanCreate); }
    if s_lower == "documentscanupdate" { return Some(Self::DocumentsCanUpdate); }
    if s_lower == "documentscandelete" { return Some(Self::DocumentsCanDelete); }
    if s_lower == "documentscanshare" { return Some(Self::DocumentsCanShare); }
    if s_lower == "documentscanexport" { return Some(Self::DocumentsCanExport); }
    if s_lower == "documentscanmanagetemplates" { return Some(Self::DocumentsCanManageTemplates); }
    if s_lower == "documentscanmanagefolders" { return Some(Self::DocumentsCanManageFolders); }
    if s_lower == "documentscancomment" { return Some(Self::DocumentsCanComment); }
    if s_lower == "documentscantrackchanges" { return Some(Self::DocumentsCanTrackChanges); }
    if s_lower == "spreadsheetscanread" { return Some(Self::SpreadsheetsCanRead); }
    if s_lower == "spreadsheetscancreate" { return Some(Self::SpreadsheetsCanCreate); }
    if s_lower == "spreadsheetscanupdate" { return Some(Self::SpreadsheetsCanUpdate); }
    if s_lower == "spreadsheetscandelete" { return Some(Self::SpreadsheetsCanDelete); }
    if s_lower == "spreadsheetscanshare" { return Some(Self::SpreadsheetsCanShare); }
    if s_lower == "spreadsheetscanexport" { return Some(Self::SpreadsheetsCanExport); }
    if s_lower == "spreadsheetscanimport" { return Some(Self::SpreadsheetsCanImport); }
    if s_lower == "spreadsheetscanmanageformulas" { return Some(Self::SpreadsheetsCanManageFormulas); }
    if s_lower == "spreadsheetscanmanagecharts" { return Some(Self::SpreadsheetsCanManageCharts); }
    if s_lower == "presentationscanread" { return Some(Self::PresentationsCanRead); }
    if s_lower == "presentationscancreate" { return Some(Self::PresentationsCanCreate); }
    if s_lower == "presentationscanupdate" { return Some(Self::PresentationsCanUpdate); }
    if s_lower == "presentationscandelete" { return Some(Self::PresentationsCanDelete); }
    if s_lower == "presentationscanpresent" { return Some(Self::PresentationsCanPresent); }
    if s_lower == "presentationscanexport" { return Some(Self::PresentationsCanExport); }
    if s_lower == "meetingscancreate" { return Some(Self::MeetingsCanCreate); }
    if s_lower == "meetingscanjoin" { return Some(Self::MeetingsCanJoin); }
    if s_lower == "meetingscanmanagerooms" { return Some(Self::MeetingsCanManageRooms); }
    if s_lower == "meetingscanrecord" { return Some(Self::MeetingsCanRecord); }
    if s_lower == "meetingscansharescreen" { return Some(Self::MeetingsCanShareScreen); }
    if s_lower == "meetingscanmanageparticipants" { return Some(Self::MeetingsCanManageParticipants); }
    if s_lower == "meetingscanmanagesettings" { return Some(Self::MeetingsCanManageSettings); }
    if s_lower == "meetingscanadmin" { return Some(Self::MeetingsCanAdmin); }
    if s_lower == "chatcansendmessages" { return Some(Self::ChatCanSendMessages); }
    if s_lower == "chatcanreadmessages" { return Some(Self::ChatCanReadMessages); }
    if s_lower == "chatcandeletemessages" { return Some(Self::ChatCanDeleteMessages); }
    if s_lower == "chatcanviewconversations" { return Some(Self::ChatCanViewConversations); }
    if s_lower == "chatcanmanagebots" { return Some(Self::ChatCanManageBots); }
    if s_lower == "chatcancreatebots" { return Some(Self::ChatCanCreateBots); }
    if s_lower == "chatcaneditbots" { return Some(Self::ChatCanEditBots); }
    if s_lower == "chatcandeletebots" { return Some(Self::ChatCanDeleteBots); }
    if s_lower == "chatcanpublishbots" { return Some(Self::ChatCanPublishBots); }
    if s_lower == "chatcanviewbots" { return Some(Self::ChatCanViewBots); }
    if s_lower == "chatcanexecutetools" { return Some(Self::ChatCanExecuteTools); }
    if s_lower == "chatcanmanageknowledgebase" { return Some(Self::ChatCanManageKnowledgeBase); }
    if s_lower == "chatcanreadknowledgebase" { return Some(Self::ChatCanReadKnowledgeBase); }
    if s_lower == "chatcanwriteknowledgebase" { return Some(Self::ChatCanWriteKnowledgeBase); }
    if s_lower == "chatcanadminknowledgebase" { return Some(Self::ChatCanAdminKnowledgeBase); }
    if s_lower == "chatcanconfigurebots" { return Some(Self::ChatCanConfigureBots); }
    if s_lower == "taskscancreate" { return Some(Self::TasksCanCreate); }
    if s_lower == "taskscanread" { return Some(Self::TasksCanRead); }
    if s_lower == "taskscanupdate" { return Some(Self::TasksCanUpdate); }
    if s_lower == "taskscandelete" { return Some(Self::TasksCanDelete); }
    if s_lower == "taskscanexecute" { return Some(Self::TasksCanExecute); }
    if s_lower == "taskscanassign" { return Some(Self::TasksCanAssign); }
    if s_lower == "taskscanmanageprojects" { return Some(Self::TasksCanManageProjects); }
    if s_lower == "taskscanmanageworkflows" { return Some(Self::TasksCanManageWorkflows); }
    if s_lower == "taskscanmanageautotask" { return Some(Self::TasksCanManageAutoTask); }
    if s_lower == "aitoolscanmanagellm" { return Some(Self::AiToolsCanManageLlm); }
    if s_lower == "aitoolscanconfigurellm" { return Some(Self::AiToolsCanConfigureLlm); }
    if s_lower == "aitoolscanmanagemodels" { return Some(Self::AiToolsCanManageModels); }
    if s_lower == "aitoolscanmanageprompts" { return Some(Self::AiToolsCanManagePrompts); }
    if s_lower == "aitoolscandesignscripts" { return Some(Self::AiToolsCanDesignScripts); }
    if s_lower == "aitoolscaneditscripts" { return Some(Self::AiToolsCanEditScripts); }
    if s_lower == "aitoolscanmanageautotask" { return Some(Self::AiToolsCanManageAutotask); }
    if s_lower == "aitoolscanmanagetraining" { return Some(Self::AiToolsCanManageTraining); }
    if s_lower == "aitoolscanmanagevibe" { return Some(Self::AiToolsCanManageVibe); }
    if s_lower == "aitoolscanmanagemcp" { return Some(Self::AiToolsCanManageMcp); }
    if s_lower == "businessintelligencecanviewdashboard" { return Some(Self::BusinessIntelligenceCanViewDashboard); }
    if s_lower == "businessintelligencecanviewreports" { return Some(Self::BusinessIntelligenceCanViewReports); }
    if s_lower == "businessintelligencecancreatereports" { return Some(Self::BusinessIntelligenceCanCreateReports); }
    if s_lower == "businessintelligencecaneditreports" { return Some(Self::BusinessIntelligenceCanEditReports); }
    if s_lower == "businessintelligencecandeletereports" { return Some(Self::BusinessIntelligenceCanDeleteReports); }
    if s_lower == "businessintelligencecanexportreports" { return Some(Self::BusinessIntelligenceCanExportReports); }
    if s_lower == "businessintelligencecanviewmetrics" { return Some(Self::BusinessIntelligenceCanViewMetrics); }
    if s_lower == "businessintelligencecanmanagedashboards" { return Some(Self::BusinessIntelligenceCanManageDashboards); }
    if s_lower == "businessintelligencecantrace" { return Some(Self::BusinessIntelligenceCanTrace); }
    if s_lower == "businessintelligencecanmonitorperformance" { return Some(Self::BusinessIntelligenceCanMonitorPerformance); }
    if s_lower == "businessintelligencecanviewanalytics" { return Some(Self::BusinessIntelligenceCanViewAnalytics); }
    if s_lower == "businessintelligencecanexportanalytics" { return Some(Self::BusinessIntelligenceCanExportAnalytics); }
    if s_lower == "integrationscanmanagewebhooks" { return Some(Self::IntegrationsCanManageWebhooks); }
    if s_lower == "integrationscanmanageapikeys" { return Some(Self::IntegrationsCanManageApiKeys); }
    if s_lower == "integrationscanconnectsources" { return Some(Self::IntegrationsCanConnectSources); }
    if s_lower == "integrationscanmanagesocialmedia" { return Some(Self::IntegrationsCanManageSocialMedia); }
    if s_lower == "integrationscanmanagewhatsapp" { return Some(Self::IntegrationsCanManageWhatsApp); }
    if s_lower == "integrationscanmanagetelegram" { return Some(Self::IntegrationsCanManageTelegram); }
    if s_lower == "integrationscanmanagemsteams" { return Some(Self::IntegrationsCanManageMsTeams); }
    if s_lower == "integrationscanmanageinstagram" { return Some(Self::IntegrationsCanManageInstagram); }
    if s_lower == "integrationscanmanageimap" { return Some(Self::IntegrationsCanManageImap); }
    if s_lower == "integrationscanmanagegoogle" { return Some(Self::IntegrationsCanManageGoogle); }
    if s_lower == "integrationscanmanagemicrosoft" { return Some(Self::IntegrationsCanManageMicrosoft); }
    if s_lower == "integrationscanmanagechannels" { return Some(Self::IntegrationsCanManageChannels); }
    None
    }
}

