use super::Permission;

impl Permission {
    pub(crate) fn from_alias_chunk3(s_lower: &str) -> Option<Self> {
    if s_lower == "integrations.manage.webhooks" { return Some(Self::IntegrationsCanManageWebhooks); }
    if s_lower == "integrations:manage:apikeys" { return Some(Self::IntegrationsCanManageApiKeys); }
    if s_lower == "integrations.manage.apikeys" { return Some(Self::IntegrationsCanManageApiKeys); }
    if s_lower == "integrations:connect:sources" { return Some(Self::IntegrationsCanConnectSources); }
    if s_lower == "integrations.connect.sources" { return Some(Self::IntegrationsCanConnectSources); }
    if s_lower == "integrations:manage:socialmedia" { return Some(Self::IntegrationsCanManageSocialMedia); }
    if s_lower == "integrations.manage.socialmedia" { return Some(Self::IntegrationsCanManageSocialMedia); }
    if s_lower == "integrations:manage:whatsapp" { return Some(Self::IntegrationsCanManageWhatsApp); }
    if s_lower == "integrations.manage.whatsapp" { return Some(Self::IntegrationsCanManageWhatsApp); }
    if s_lower == "integrations:manage:telegram" { return Some(Self::IntegrationsCanManageTelegram); }
    if s_lower == "integrations.manage.telegram" { return Some(Self::IntegrationsCanManageTelegram); }
    if s_lower == "integrations:manage:msteams" { return Some(Self::IntegrationsCanManageMsTeams); }
    if s_lower == "integrations.manage.msteams" { return Some(Self::IntegrationsCanManageMsTeams); }
    if s_lower == "integrations:manage:instagram" { return Some(Self::IntegrationsCanManageInstagram); }
    if s_lower == "integrations.manage.instagram" { return Some(Self::IntegrationsCanManageInstagram); }
    if s_lower == "integrations:manage:imap" { return Some(Self::IntegrationsCanManageImap); }
    if s_lower == "integrations.manage.imap" { return Some(Self::IntegrationsCanManageImap); }
    if s_lower == "integrations:manage:google" { return Some(Self::IntegrationsCanManageGoogle); }
    if s_lower == "integrations.manage.google" { return Some(Self::IntegrationsCanManageGoogle); }
    if s_lower == "integrations:manage:microsoft" { return Some(Self::IntegrationsCanManageMicrosoft); }
    if s_lower == "integrations.manage.microsoft" { return Some(Self::IntegrationsCanManageMicrosoft); }
    if s_lower == "integrations:manage:channels" { return Some(Self::IntegrationsCanManageChannels); }
    if s_lower == "integrations.manage.channels" { return Some(Self::IntegrationsCanManageChannels); }
    if s_lower == "automation:create:workflows" { return Some(Self::AutomationCanCreateWorkflows); }
    if s_lower == "automation.create.workflows" { return Some(Self::AutomationCanCreateWorkflows); }
    if s_lower == "automation:edit:workflows" { return Some(Self::AutomationCanEditWorkflows); }
    if s_lower == "automation.edit.workflows" { return Some(Self::AutomationCanEditWorkflows); }
    if s_lower == "automation:delete:workflows" { return Some(Self::AutomationCanDeleteWorkflows); }
    if s_lower == "automation.delete.workflows" { return Some(Self::AutomationCanDeleteWorkflows); }
    if s_lower == "automation:execute:workflows" { return Some(Self::AutomationCanExecuteWorkflows); }
    if s_lower == "automation.execute.workflows" { return Some(Self::AutomationCanExecuteWorkflows); }
    if s_lower == "automation:manage:triggers" { return Some(Self::AutomationCanManageTriggers); }
    if s_lower == "automation.manage.triggers" { return Some(Self::AutomationCanManageTriggers); }
    if s_lower == "automation:manage:schedules" { return Some(Self::AutomationCanManageSchedules); }
    if s_lower == "automation.manage.schedules" { return Some(Self::AutomationCanManageSchedules); }
    if s_lower == "automation:manage:eventhandlers" { return Some(Self::AutomationCanManageEventHandlers); }
    if s_lower == "automation.manage.eventhandlers" { return Some(Self::AutomationCanManageEventHandlers); }
    if s_lower == "crm:view:pipeline" { return Some(Self::CrmCanViewPipeline); }
    if s_lower == "crm.view.pipeline" { return Some(Self::CrmCanViewPipeline); }
    if s_lower == "crm:manage:leads" { return Some(Self::CrmCanManageLeads); }
    if s_lower == "crm.manage.leads" { return Some(Self::CrmCanManageLeads); }
    if s_lower == "crm:manage:contacts" { return Some(Self::CrmCanManageContacts); }
    if s_lower == "crm.manage.contacts" { return Some(Self::CrmCanManageContacts); }
    if s_lower == "crm:manage:deals" { return Some(Self::CrmCanManageDeals); }
    if s_lower == "crm.manage.deals" { return Some(Self::CrmCanManageDeals); }
    if s_lower == "crm:view:reports" { return Some(Self::CrmCanViewReports); }
    if s_lower == "crm.view.reports" { return Some(Self::CrmCanViewReports); }
    if s_lower == "crm:export:reports" { return Some(Self::CrmCanExportReports); }
    if s_lower == "crm.export.reports" { return Some(Self::CrmCanExportReports); }
    if s_lower == "crm:manage:forecast" { return Some(Self::CrmCanManageForecast); }
    if s_lower == "crm.manage.forecast" { return Some(Self::CrmCanManageForecast); }
    if s_lower == "campaigns:create:*" { return Some(Self::CampaignsCanCreate); }
    if s_lower == "campaigns.create.*" { return Some(Self::CampaignsCanCreate); }
    if s_lower == "campaigns:edit:*" { return Some(Self::CampaignsCanEdit); }
    if s_lower == "campaigns.edit.*" { return Some(Self::CampaignsCanEdit); }
    if s_lower == "campaigns:delete:*" { return Some(Self::CampaignsCanDelete); }
    if s_lower == "campaigns.delete.*" { return Some(Self::CampaignsCanDelete); }
    if s_lower == "campaigns:execute:*" { return Some(Self::CampaignsCanExecute); }
    if s_lower == "campaigns.execute.*" { return Some(Self::CampaignsCanExecute); }
    if s_lower == "campaigns:view:analytics" { return Some(Self::CampaignsCanViewAnalytics); }
    if s_lower == "campaigns.view.analytics" { return Some(Self::CampaignsCanViewAnalytics); }
    if s_lower == "campaigns:manage:segments" { return Some(Self::CampaignsCanManageSegments); }
    if s_lower == "campaigns.manage.segments" { return Some(Self::CampaignsCanManageSegments); }
    if s_lower == "products:view:catalog" { return Some(Self::ProductsCanViewCatalog); }
    if s_lower == "products.view.catalog" { return Some(Self::ProductsCanViewCatalog); }
    if s_lower == "products:create:products" { return Some(Self::ProductsCanCreateProducts); }
    if s_lower == "products.create.products" { return Some(Self::ProductsCanCreateProducts); }
    if s_lower == "products:edit:products" { return Some(Self::ProductsCanEditProducts); }
    if s_lower == "products.edit.products" { return Some(Self::ProductsCanEditProducts); }
    if s_lower == "products:delete:products" { return Some(Self::ProductsCanDeleteProducts); }
    if s_lower == "products.delete.products" { return Some(Self::ProductsCanDeleteProducts); }
    if s_lower == "products:create:services" { return Some(Self::ProductsCanCreateServices); }
    if s_lower == "products.create.services" { return Some(Self::ProductsCanCreateServices); }
    if s_lower == "products:edit:services" { return Some(Self::ProductsCanEditServices); }
    if s_lower == "products.edit.services" { return Some(Self::ProductsCanEditServices); }
    if s_lower == "products:delete:services" { return Some(Self::ProductsCanDeleteServices); }
    if s_lower == "products.delete.services" { return Some(Self::ProductsCanDeleteServices); }
    if s_lower == "products:manage:pricelists" { return Some(Self::ProductsCanManagePriceLists); }
    if s_lower == "products.manage.pricelists" { return Some(Self::ProductsCanManagePriceLists); }
    if s_lower == "tickets:create:*" { return Some(Self::TicketsCanCreate); }
    if s_lower == "tickets.create.*" { return Some(Self::TicketsCanCreate); }
    if s_lower == "tickets:read:*" { return Some(Self::TicketsCanRead); }
    if s_lower == "tickets.read.*" { return Some(Self::TicketsCanRead); }
    if s_lower == "tickets:update:*" { return Some(Self::TicketsCanUpdate); }
    if s_lower == "tickets.update.*" { return Some(Self::TicketsCanUpdate); }
    if s_lower == "tickets:delete:*" { return Some(Self::TicketsCanDelete); }
    if s_lower == "tickets.delete.*" { return Some(Self::TicketsCanDelete); }
    if s_lower == "tickets:assign:*" { return Some(Self::TicketsCanAssign); }
    if s_lower == "tickets.assign.*" { return Some(Self::TicketsCanAssign); }
    if s_lower == "tickets:resolve:*" { return Some(Self::TicketsCanResolve); }
    if s_lower == "tickets.resolve.*" { return Some(Self::TicketsCanResolve); }
    if s_lower == "tickets:manage:priorities" { return Some(Self::TicketsCanManagePriorities); }
    if s_lower == "tickets.manage.priorities" { return Some(Self::TicketsCanManagePriorities); }
    if s_lower == "tickets:view:analytics" { return Some(Self::TicketsCanViewAnalytics); }
    if s_lower == "tickets.view.analytics" { return Some(Self::TicketsCanViewAnalytics); }
    if s_lower == "tickets:manage:attendant" { return Some(Self::TicketsCanManageAttendant); }
    if s_lower == "tickets.manage.attendant" { return Some(Self::TicketsCanManageAttendant); }
    if s_lower == "people:view:directory" { return Some(Self::PeopleCanViewDirectory); }
    if s_lower == "people.view.directory" { return Some(Self::PeopleCanViewDirectory); }
    if s_lower == "people:manage:contacts" { return Some(Self::PeopleCanManageContacts); }
    if s_lower == "people.manage.contacts" { return Some(Self::PeopleCanManageContacts); }
    if s_lower == "people:manage:groups" { return Some(Self::PeopleCanManageGroups); }
    if s_lower == "people.manage.groups" { return Some(Self::PeopleCanManageGroups); }
    if s_lower == "people:manage:roles" { return Some(Self::PeopleCanManageRoles); }
    if s_lower == "people.manage.roles" { return Some(Self::PeopleCanManageRoles); }
    if s_lower == "people:import:contacts" { return Some(Self::PeopleCanImportContacts); }
    if s_lower == "people.import.contacts" { return Some(Self::PeopleCanImportContacts); }
    if s_lower == "browser:navigate:*" { return Some(Self::BrowserCanNavigate); }
    if s_lower == "browser.navigate.*" { return Some(Self::BrowserCanNavigate); }
    if s_lower == "browser:bookmark:*" { return Some(Self::BrowserCanBookmark); }
    if s_lower == "browser.bookmark.*" { return Some(Self::BrowserCanBookmark); }
    if s_lower == "browser:manage:history" { return Some(Self::BrowserCanManageHistory); }
    if s_lower == "browser.manage.history" { return Some(Self::BrowserCanManageHistory); }
    if s_lower == "browser:download:*" { return Some(Self::BrowserCanDownload); }
    if s_lower == "browser.download.*" { return Some(Self::BrowserCanDownload); }
    if s_lower == "terminal:execute:*" { return Some(Self::TerminalCanExecute); }
    if s_lower == "terminal.execute.*" { return Some(Self::TerminalCanExecute); }
    if s_lower == "terminal:view:output" { return Some(Self::TerminalCanViewOutput); }
    if s_lower == "terminal.view.output" { return Some(Self::TerminalCanViewOutput); }
    if s_lower == "terminal:manage:sessions" { return Some(Self::TerminalCanManageSessions); }
    if s_lower == "terminal.manage.sessions" { return Some(Self::TerminalCanManageSessions); }
    if s_lower == "research:search:*" { return Some(Self::ResearchCanSearch); }
    if s_lower == "research.search.*" { return Some(Self::ResearchCanSearch); }
    if s_lower == "research:manage:sources" { return Some(Self::ResearchCanManageSources); }
    if s_lower == "research.manage.sources" { return Some(Self::ResearchCanManageSources); }
    if s_lower == "research:export:results" { return Some(Self::ResearchCanExportResults); }
    if s_lower == "research.export.results" { return Some(Self::ResearchCanExportResults); }
    if s_lower == "research:manage:sessions" { return Some(Self::ResearchCanManageSessions); }
    if s_lower == "research.manage.sessions" { return Some(Self::ResearchCanManageSessions); }
    if s_lower == "social:post:*" { return Some(Self::SocialCanPost); }
    if s_lower == "social.post.*" { return Some(Self::SocialCanPost); }
    if s_lower == "social:schedule:posts" { return Some(Self::SocialCanSchedulePosts); }
    if s_lower == "social.schedule.posts" { return Some(Self::SocialCanSchedulePosts); }
    if s_lower == "social:view:feed" { return Some(Self::SocialCanViewFeed); }
    if s_lower == "social.view.feed" { return Some(Self::SocialCanViewFeed); }
    if s_lower == "social:manage:accounts" { return Some(Self::SocialCanManageAccounts); }
    if s_lower == "social.manage.accounts" { return Some(Self::SocialCanManageAccounts); }
    if s_lower == "social:view:analytics" { return Some(Self::SocialCanViewAnalytics); }
    if s_lower == "social.view.analytics" { return Some(Self::SocialCanViewAnalytics); }
    if s_lower == "video:upload:*" { return Some(Self::VideoCanUpload); }
    if s_lower == "video.upload.*" { return Some(Self::VideoCanUpload); }
    if s_lower == "video:play:*" { return Some(Self::VideoCanPlay); }
    if s_lower == "video.play.*" { return Some(Self::VideoCanPlay); }
    if s_lower == "video:edit:*" { return Some(Self::VideoCanEdit); }
    if s_lower == "video.edit.*" { return Some(Self::VideoCanEdit); }
    if s_lower == "video:delete:*" { return Some(Self::VideoCanDelete); }
    if s_lower == "video.delete.*" { return Some(Self::VideoCanDelete); }
    if s_lower == "video:manage:library" { return Some(Self::VideoCanManageLibrary); }
    if s_lower == "video.manage.library" { return Some(Self::VideoCanManageLibrary); }
    None
    }
}

