use super::Permission;

impl Permission {
    pub(crate) fn from_alias_chunk4(s_lower: &str) -> Option<Self> {
    if s_lower == "canvas:create:*" { return Some(Self::CanvasCanCreate); }
    if s_lower == "canvas.create.*" { return Some(Self::CanvasCanCreate); }
    if s_lower == "canvas:edit:*" { return Some(Self::CanvasCanEdit); }
    if s_lower == "canvas.edit.*" { return Some(Self::CanvasCanEdit); }
    if s_lower == "canvas:view:*" { return Some(Self::CanvasCanView); }
    if s_lower == "canvas.view.*" { return Some(Self::CanvasCanView); }
    if s_lower == "canvas:delete:*" { return Some(Self::CanvasCanDelete); }
    if s_lower == "canvas.delete.*" { return Some(Self::CanvasCanDelete); }
    if s_lower == "canvas:export:*" { return Some(Self::CanvasCanExport); }
    if s_lower == "canvas.export.*" { return Some(Self::CanvasCanExport); }
    if s_lower == "workspace:create:sites" { return Some(Self::WorkspaceCanCreateSites); }
    if s_lower == "workspace.create.sites" { return Some(Self::WorkspaceCanCreateSites); }
    if s_lower == "workspace:edit:sites" { return Some(Self::WorkspaceCanEditSites); }
    if s_lower == "workspace.edit.sites" { return Some(Self::WorkspaceCanEditSites); }
    if s_lower == "workspace:delete:sites" { return Some(Self::WorkspaceCanDeleteSites); }
    if s_lower == "workspace.delete.sites" { return Some(Self::WorkspaceCanDeleteSites); }
    if s_lower == "workspace:view:sites" { return Some(Self::WorkspaceCanViewSites); }
    if s_lower == "workspace.view.sites" { return Some(Self::WorkspaceCanViewSites); }
    if s_lower == "workspace:manage:pages" { return Some(Self::WorkspaceCanManagePages); }
    if s_lower == "workspace.manage.pages" { return Some(Self::WorkspaceCanManagePages); }
    if s_lower == "workspace:manage:databases" { return Some(Self::WorkspaceCanManageDatabases); }
    if s_lower == "workspace.manage.databases" { return Some(Self::WorkspaceCanManageDatabases); }
    if s_lower == "goals:create:*" { return Some(Self::GoalsCanCreate); }
    if s_lower == "goals.create.*" { return Some(Self::GoalsCanCreate); }
    if s_lower == "goals:edit:*" { return Some(Self::GoalsCanEdit); }
    if s_lower == "goals.edit.*" { return Some(Self::GoalsCanEdit); }
    if s_lower == "goals:delete:*" { return Some(Self::GoalsCanDelete); }
    if s_lower == "goals.delete.*" { return Some(Self::GoalsCanDelete); }
    if s_lower == "goals:view:*" { return Some(Self::GoalsCanView); }
    if s_lower == "goals.view.*" { return Some(Self::GoalsCanView); }
    if s_lower == "goals:track:progress" { return Some(Self::GoalsCanTrackProgress); }
    if s_lower == "goals.track.progress" { return Some(Self::GoalsCanTrackProgress); }
    if s_lower == "learn:view:courses" { return Some(Self::LearnCanViewCourses); }
    if s_lower == "learn.view.courses" { return Some(Self::LearnCanViewCourses); }
    if s_lower == "learn:enroll:*" { return Some(Self::LearnCanEnroll); }
    if s_lower == "learn.enroll.*" { return Some(Self::LearnCanEnroll); }
    if s_lower == "learn:create:courses" { return Some(Self::LearnCanCreateCourses); }
    if s_lower == "learn.create.courses" { return Some(Self::LearnCanCreateCourses); }
    if s_lower == "learn:edit:courses" { return Some(Self::LearnCanEditCourses); }
    if s_lower == "learn.edit.courses" { return Some(Self::LearnCanEditCourses); }
    if s_lower == "learn:delete:courses" { return Some(Self::LearnCanDeleteCourses); }
    if s_lower == "learn.delete.courses" { return Some(Self::LearnCanDeleteCourses); }
    if s_lower == "learn:manage:modules" { return Some(Self::LearnCanManageModules); }
    if s_lower == "learn.manage.modules" { return Some(Self::LearnCanManageModules); }
    if s_lower == "code:read:*" { return Some(Self::CodeCanRead); }
    if s_lower == "code.read.*" { return Some(Self::CodeCanRead); }
    if s_lower == "code:write:*" { return Some(Self::CodeCanWrite); }
    if s_lower == "code.write.*" { return Some(Self::CodeCanWrite); }
    if s_lower == "code:delete:*" { return Some(Self::CodeCanDelete); }
    if s_lower == "code.delete.*" { return Some(Self::CodeCanDelete); }
    if s_lower == "code:execute:*" { return Some(Self::CodeCanExecute); }
    if s_lower == "code.execute.*" { return Some(Self::CodeCanExecute); }
    if s_lower == "code:manage:git" { return Some(Self::CodeCanManageGit); }
    if s_lower == "code.manage.git" { return Some(Self::CodeCanManageGit); }
    if s_lower == "code:commit:*" { return Some(Self::CodeCanCommit); }
    if s_lower == "code.commit.*" { return Some(Self::CodeCanCommit); }
    if s_lower == "code:push:*" { return Some(Self::CodeCanPush); }
    if s_lower == "code.push.*" { return Some(Self::CodeCanPush); }
    if s_lower == "code:deploy:*" { return Some(Self::CodeCanDeploy); }
    if s_lower == "code.deploy.*" { return Some(Self::CodeCanDeploy); }
    if s_lower == "database:query:*" { return Some(Self::DatabaseCanQuery); }
    if s_lower == "database.query.*" { return Some(Self::DatabaseCanQuery); }
    if s_lower == "database:read:tables" { return Some(Self::DatabaseCanReadTables); }
    if s_lower == "database.read.tables" { return Some(Self::DatabaseCanReadTables); }
    if s_lower == "database:write:tables" { return Some(Self::DatabaseCanWriteTables); }
    if s_lower == "database.write.tables" { return Some(Self::DatabaseCanWriteTables); }
    if s_lower == "database:delete:tables" { return Some(Self::DatabaseCanDeleteTables); }
    if s_lower == "database.delete.tables" { return Some(Self::DatabaseCanDeleteTables); }
    if s_lower == "database:admin:tables" { return Some(Self::DatabaseCanAdminTables); }
    if s_lower == "database.admin.tables" { return Some(Self::DatabaseCanAdminTables); }
    if s_lower == "database:manage:migrations" { return Some(Self::DatabaseCanManageMigrations); }
    if s_lower == "database.manage.migrations" { return Some(Self::DatabaseCanManageMigrations); }
    if s_lower == "templates:view:*" { return Some(Self::TemplatesCanView); }
    if s_lower == "templates.view.*" { return Some(Self::TemplatesCanView); }
    if s_lower == "templates:create:*" { return Some(Self::TemplatesCanCreate); }
    if s_lower == "templates.create.*" { return Some(Self::TemplatesCanCreate); }
    if s_lower == "templates:edit:*" { return Some(Self::TemplatesCanEdit); }
    if s_lower == "templates.edit.*" { return Some(Self::TemplatesCanEdit); }
    if s_lower == "templates:delete:*" { return Some(Self::TemplatesCanDelete); }
    if s_lower == "templates.delete.*" { return Some(Self::TemplatesCanDelete); }
    if s_lower == "templates:apply:*" { return Some(Self::TemplatesCanApply); }
    if s_lower == "templates.apply.*" { return Some(Self::TemplatesCanApply); }
    if s_lower == "lists:view:*" { return Some(Self::ListsCanView); }
    if s_lower == "lists.view.*" { return Some(Self::ListsCanView); }
    if s_lower == "lists:create:*" { return Some(Self::ListsCanCreate); }
    if s_lower == "lists.create.*" { return Some(Self::ListsCanCreate); }
    if s_lower == "lists:edit:*" { return Some(Self::ListsCanEdit); }
    if s_lower == "lists.edit.*" { return Some(Self::ListsCanEdit); }
    if s_lower == "lists:delete:*" { return Some(Self::ListsCanDelete); }
    if s_lower == "lists.delete.*" { return Some(Self::ListsCanDelete); }
    if s_lower == "lists:export:*" { return Some(Self::ListsCanExport); }
    if s_lower == "lists.export.*" { return Some(Self::ListsCanExport); }
    if s_lower == "lists:import:*" { return Some(Self::ListsCanImport); }
    if s_lower == "lists.import.*" { return Some(Self::ListsCanImport); }
    if s_lower == "manage_users" { return Some(Self::ManageUsers); }
    if s_lower == "users.manage" { return Some(Self::ManageUsers); }
    if s_lower == "manage_bots" { return Some(Self::ManageBots); }
    if s_lower == "bots.manage" { return Some(Self::ManageBots); }
    if s_lower == "view_analytics" { return Some(Self::ViewAnalytics); }
    if s_lower == "analytics.view" { return Some(Self::ViewAnalytics); }
    if s_lower == "manage_settings" { return Some(Self::ManageSettings); }
    if s_lower == "settings.manage" { return Some(Self::ManageSettings); }
    if s_lower == "execute_tasks" { return Some(Self::ExecuteTasks); }
    if s_lower == "tasks.execute" { return Some(Self::ExecuteTasks); }
    if s_lower == "view_logs" { return Some(Self::ViewLogs); }
    if s_lower == "logs.view" { return Some(Self::ViewLogs); }
    if s_lower == "manage_secrets" { return Some(Self::ManageSecrets); }
    if s_lower == "secrets.manage" { return Some(Self::ManageSecrets); }
    if s_lower == "access_api" { return Some(Self::AccessApi); }
    if s_lower == "api.access" { return Some(Self::AccessApi); }
    if s_lower == "manage_files" { return Some(Self::ManageFiles); }
    if s_lower == "files.manage" { return Some(Self::ManageFiles); }
    if s_lower == "send_messages" { return Some(Self::SendMessages); }
    if s_lower == "messages.send" { return Some(Self::SendMessages); }
    if s_lower == "view_conversations" { return Some(Self::ViewConversations); }
    if s_lower == "conversations.view" { return Some(Self::ViewConversations); }
    if s_lower == "manage_webhooks" { return Some(Self::ManageWebhooks); }
    if s_lower == "webhooks.manage" { return Some(Self::ManageWebhooks); }
    if s_lower == "manage_integrations" { return Some(Self::ManageIntegrations); }
    if s_lower == "integrations.manage" { return Some(Self::ManageIntegrations); }
    if s_lower == "manageusers" { return Some(Self::ManageUsers); }
    if s_lower == "managebots" { return Some(Self::ManageBots); }
    if s_lower == "viewanalytics" { return Some(Self::ViewAnalytics); }
    if s_lower == "managesettings" { return Some(Self::ManageSettings); }
    if s_lower == "executetasks" { return Some(Self::ExecuteTasks); }
    if s_lower == "viewlogs" { return Some(Self::ViewLogs); }
    if s_lower == "managesecrets" { return Some(Self::ManageSecrets); }
    if s_lower == "accessapi" { return Some(Self::AccessApi); }
    if s_lower == "managefiles" { return Some(Self::ManageFiles); }
    if s_lower == "sendmessages" { return Some(Self::SendMessages); }
    if s_lower == "viewconversations" { return Some(Self::ViewConversations); }
    if s_lower == "managewebhooks" { return Some(Self::ManageWebhooks); }
    if s_lower == "manageintegrations" { return Some(Self::ManageIntegrations); }
    if s_lower == "administrationcanmanageorganization" { return Some(Self::AdministrationCanManageOrganization); }
    if s_lower == "administrationcanmanagemembers" { return Some(Self::AdministrationCanManageMembers); }
    if s_lower == "administrationcanviewmembers" { return Some(Self::AdministrationCanViewMembers); }
    if s_lower == "administrationcanmanagesettings" { return Some(Self::AdministrationCanManageSettings); }
    if s_lower == "administrationcanmanagebilling" { return Some(Self::AdministrationCanManageBilling); }
    if s_lower == "administrationcanviewbilling" { return Some(Self::AdministrationCanViewBilling); }
    if s_lower == "administrationcanmanageauditlog" { return Some(Self::AdministrationCanManageAuditLog); }
    if s_lower == "administrationcanviewauditlog" { return Some(Self::AdministrationCanViewAuditLog); }
    if s_lower == "administrationcanmanagedns" { return Some(Self::AdministrationCanManageDns); }
    if s_lower == "administrationcanmanageonboarding" { return Some(Self::AdministrationCanManageOnboarding); }
    if s_lower == "administrationcanmanageroles" { return Some(Self::AdministrationCanManageRoles); }
    if s_lower == "administrationcanmanagegroups" { return Some(Self::AdministrationCanManageGroups); }
    None
    }
}

