//! SharePoint model types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A SharePoint site.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SharePointSite {
    /// Site ID.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Site URL.
    pub web_url: String,
    /// When the site was last modified (UTC).
    pub last_modified: Option<DateTime<Utc>>,
}

/// A column in a SharePoint list.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListColumn {
    /// Internal name.
    pub name: String,
    /// Display name.
    pub display_name: String,
    /// Column type (e.g. "text", "number", "dateTime", "boolean").
    pub column_type: String,
    /// Whether the column is required.
    pub required: bool,
}

/// A SharePoint list.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SharePointList {
    /// List ID.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Description.
    pub description: Option<String>,
    /// All columns in the list.
    pub columns: Vec<ListColumn>,
}

/// A single list item.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SharePointListItem {
    /// Server-assigned internal ID (UUID generated by the connector).
    pub id: Uuid,
    /// SharePoint item ID.
    pub sp_item_id: u64,
    /// Field values, encoded as a JSON object.
    pub fields: serde_json::Value,
    /// When the item was last modified.
    pub modified_at: Option<DateTime<Utc>>,
    /// Who modified it (user principal name).
    pub modified_by: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn column_roundtrip() {
        let col = ListColumn {
            name: "Title".to_string(),
            display_name: "Title".to_string(),
            column_type: "text".to_string(),
            required: true,
        };
        assert_eq!(col.name, "Title");
        assert!(col.required);
    }
}
