//! LLM-first project scaffolding (#1312).
//!
//! A project created with a "what do you want to build?" description must
//! start from LLM-generated code, not from a hardcoded template: the
//! description IS the starting point the agent then iterates on. This module
//! asks the LLM for a small set of starter files (`{path: content}` JSON),
//! validates them against workspace rules and writes them into the project
//! workspace. The built-in template (`templates::seed_project_workspace`)
//! remains only as the offline/error fallback so project creation never
//! breaks when the LLM is unreachable.

use log::{info, warn};
use std::time::Duration;

/// Upper bounds for LLM-produced starters (a scaffold is a starting point,
/// not a full app — small keeps it reviewable and fast).
const MAX_SCAFFOLD_FILES: usize = 12;
const MAX_SCAFFOLD_BYTES: usize = 512 * 1024;
const SCAFFOLD_TIMEOUT_SECS: u64 = 90;

/// Seeding mode: which source produced the starter files.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScaffoldSource {
    /// Starter files generated by the LLM from the user's description.
    Llm,
    /// Hardcoded built-in template (LLM unavailable/failed/empty prompt).
    Template,
    /// Workspace was already populated; nothing was written.
    Existing,
}

/// Scaffolds the starter files for a fresh project workspace.
///
/// The LLM prompt is built from `description` (the New Project dialog's
/// "what do you want to build?"); when empty, the project name/type alone is
/// used so even prompt-less creation is LLM-driven. Every failure path
/// falls back to the built-in template (`templates::seed_project_workspace`)
/// so creation remains robust offline. Never clobbers a non-empty workspace.
///
/// Bot projects keep the README starter (their runtime is `.gbdialog`, not
/// the workspace); app/site workspaces are served by Run, so they get real
/// code.
pub async fn scaffold_project_workspace(
    key: &str,
    project_name: &str,
    project_type: &str,
    framework: Option<&str>,
    description: Option<&str>,
) -> Result<ScaffoldSource, String> {
    log::info!(
        "Vibe scaffold: entering for {key} type={project_type} desc={}",
        description.map(str::len).unwrap_or(0)
    );
    if workspace_has_files(key)? {
        return Ok(ScaffoldSource::Existing);
    }
    let is_bot = project_type.eq_ignore_ascii_case("bot");
    if !is_bot {
        if let Some(files) = llm_scaffold(project_name, project_type, framework, description).await
        {
            match write_files(key, &files) {
                Ok(()) => {
                    info!(
                        "Vibe: scaffolded workspace '{key}' with {} LLM-generated files",
                        files.len()
                    );
                    return Ok(ScaffoldSource::Llm);
                }
                Err(e) => {
                    warn!("Vibe: LLM scaffold for '{key}' rejected, using template: {e}");
                }
            }
        }
    }
    crate::templates::seed_project_workspace(key, project_name, project_type, framework)?;
    Ok(ScaffoldSource::Template)
}

/// True when the workspace at `workspace_root()/{key}` already contains files.
fn workspace_has_files(key: &str) -> Result<bool, String> {
    let key = crate::harness::sanitize_project_id(key)?;
    let dir = crate::harness::workspace_root().join(&key);
    if !dir.is_dir() {
        log::info!("Vibe scaffold: workspace dir missing for {key} at {}", dir.display());
        return Ok(false);
    }
    let mut entries = std::fs::read_dir(&dir).map_err(|e| format!("read workspace {key}: {e}"))?;
    let has = entries.next().is_some();
    log::info!("Vibe scaffold: workspace {key} has_files={has}");
    Ok(has)
}

/// Asks the LLM for a `{path: content}` map of starter files. Returns `None`
/// when no LLM is configured or every attempt failed (caller falls back).
async fn llm_scaffold(
    project_name: &str,
    project_type: &str,
    framework: Option<&str>,
    description: Option<&str>,
) -> Option<serde_json::Map<String, serde_json::Value>> {
    let settings = crate::llm_client::resolve_llm(None, None, None);
    if settings.url.is_empty() || settings.key.is_empty() {
        warn!("Vibe scaffold: no LLM configured (LLM_URL/LLM_KEY), using template");
        return None;
    }
    let fw = framework.unwrap_or("").trim();
    let brief = description
        .map(str::trim)
        .filter(|d| !d.is_empty())
        .map(|d| format!(" The user described it as: \"{d}\""))
        .unwrap_or_default();
    let system = "You are the Vibe scaffolding engine. The user is creating a new project and \
                  the starter files you produce are the starting point an autonomous coding agent \
                  will iterate on. Respond with ONLY a JSON object mapping relative file paths to \
                  complete file contents. Requirements: minimal but functional starter app; zero or \
                  very few external dependencies (stdlib/serverless-friendly); files must be \
                  runnable immediately; include a README.md explaining how to run it; prefer 3-8 \
                  files; no absolute paths, no '..', no build artifacts, no secrets.";
    let prompt = format!(
        "Create the starter application for a {project_type} project named \"{project_name}\"\
         {brief}. Framework: {fw}. Project kind notes: website projects are static sites (index.html \
         with inline CSS/JS, no CDN); apps projects run as an always-on service (node → index.js \
         with a /health endpoint reading PORT env, python → app.py). Return the JSON file map now."
    );
    let result = tokio::time::timeout(
        Duration::from_secs(SCAFFOLD_TIMEOUT_SECS),
        crate::llm_client::chat_completion(&settings, system, &prompt),
    )
    .await;
    let raw = match result {
        Ok(Ok(text)) => text,
        Ok(Err(e)) => {
            warn!("Vibe scaffold: LLM call failed, using template: {e}");
            return None;
        }
        Err(_) => {
            warn!("Vibe scaffold: LLM call timed out after {SCAFFOLD_TIMEOUT_SECS}s, using template");
            return None;
        }
    };
    let json = crate::llm_client::extract_json(&raw);
    match serde_json::from_str::<serde_json::Map<String, serde_json::Value>>(&json) {
        Ok(map) if !map.is_empty() => Some(map),
        Ok(_) => {
            warn!(
                "Vibe scaffold: LLM returned an empty file map, using template (raw head: {:.200})",
                raw.replace('\n', " ")
            );
            None
        }
        Err(e) => {
            warn!(
                "Vibe scaffold: LLM response was not a JSON file map, using template: {e} (raw head: {:.200})",
                raw.replace('\n', " ")
            );
            None
        }
    }
}

/// Validates and writes an LLM-produced file map into the workspace.
fn write_files(
    key: &str,
    files: &serde_json::Map<String, serde_json::Value>,
) -> Result<(), String> {
    if files.len() > MAX_SCAFFOLD_FILES {
        return Err(format!(
            "scaffold has {} files (max {MAX_SCAFFOLD_FILES})",
            files.len()
        ));
    }
    let mut total = 0usize;
    for (path, content) in files {
        let path = path.trim();
        if path.is_empty()
            || path.starts_with('/')
            || path.contains("..")
            || path.contains('\\')
            || path.contains(':')
        {
            return Err(format!("scaffold rejected unsafe path {path:?}"));
        }
        let text = match content.as_str() {
            Some(s) => s,
            None => return Err(format!("scaffold file {path:?} is not a string")),
        };
        // Platform rule: NEVER use CDN links — all assets must be local. The
        // scaffold prompt already instructs the model, but LLMs occasionally
        // emit `unpkg`/`cdnjs`/`<script src="https://…">` tags anyway. Strip
        // remote resource tags (inline logic stays) so the app works offline
        // and complies with the local-assets directive.
        let text = strip_remote_resources(text);
        total += text.len();
        if total > MAX_SCAFFOLD_BYTES {
            return Err(format!(
                "scaffold exceeds {MAX_SCAFFOLD_BYTES} bytes (at {path:?})"
            ));
        }
        crate::harness::write_rel_file(key, path, text.as_bytes())?;
    }
    if !files.keys().any(|p| p.trim() == "README.md") {
        crate::harness::write_rel_file(key, "README.md", b"# Project\n\nScaffolded from your description by Vibe's AI.\n")?;
    }
    Ok(())
}

/// Removes remote (CDN) resource references from scaffolded HTML/CSS/JS so
/// every emitted app respects the local-assets-only directive. Tags whose
/// `src`/`href` point at `http(s)://` are dropped; the surrounding inline
/// code is preserved.
fn strip_remote_resources(text: &str) -> String {
    use std::sync::OnceLock;
    use std::sync::atomic::{AtomicBool, Ordering};
    static STRIPPED: OnceLock<AtomicBool> = OnceLock::new();

    // <script src="http…">…</script> (self-closing or paired)
    let script = regex::Regex::new(
        r#"(?is)<script\b[^>]*\ssrc\s*=\s*["']https?://[^"']*["'][^>]*>.*?</script>"#,
    )
    .ok();
    // <link href="http…" …> and <link rel=… href="http…" …>
    let link = regex::Regex::new(
        r#"(?is)<link\b[^>]*\shref\s*=\s*["']https?://[^"']*["'][^>]*/?>"#,
    )
    .ok();
    // CSS @import url(http…);
    let css_import = regex::Regex::new(
        r#"(?i)@import\s+url\(\s*["']?https?://[^)]*\)?\s*;?"#,
    )
    .ok();

    let mut out = text.to_string();
    if let Some(re) = script.as_ref() {
        out = re.replace_all(&out, "<!-- remote script removed (local assets only) -->").into_owned();
    }
    if let Some(re) = link.as_ref() {
        out = re.replace_all(&out, "<!-- remote stylesheet removed (local assets only) -->").into_owned();
    }
    if let Some(re) = css_import.as_ref() {
        out = re.replace_all(&out, "/* remote import removed (local assets only) */").into_owned();
    }
    if out != text {
        let flag = STRIPPED.get_or_init(|| AtomicBool::new(false));
        if !flag.swap(true, Ordering::Relaxed) {
            warn!("Vibe scaffold: stripped remote CDN references from LLM output (local-assets-only rule)");
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn falls_back_to_template_without_llm() {
        let _guard = crate::harness::WORKSPACE_ENV_LOCK
            .lock()
            .expect("workspace env lock");
        let previous = std::env::var_os("VIBE_WORKSPACE_ROOT");
        let tmp =
            std::env::temp_dir().join(format!("vibe-scaffold-test-{}", uuid::Uuid::new_v4()));
        std::env::set_var("VIBE_WORKSPACE_ROOT", &tmp);
        // The Vault-backed resolve_llm (llm_client.rs) can supply credentials
        // even with LLM_URL/LLM_KEY unset, which would send this test's
        // scaffold call to the real LLM (slow, environment-dependent). A
        // guaranteed-invalid LLM_URL forces the documented template fallback
        // deterministically.
        let previous_llm = std::env::var_os("LLM_URL");
        std::env::set_var("LLM_URL", "http://127.0.0.1:9");
        let previous_key = std::env::var_os("LLM_KEY");
        std::env::set_var("LLM_KEY", "test-no-key");

        let key = "calc";
        let source =
            scaffold_project_workspace(key, "Calculator", "apps", Some("node"), None).await
                .expect("scaffold");
        assert_eq!(source, ScaffoldSource::Template);
        let entries = crate::harness::list_rel(key, "", 0).expect("list");
        assert!(
            entries.iter().any(|e| e == "calc.js"),
            "template fallback must seed calculator starter: {entries:?}"
        );

        // Second call is a no-op (workspace populated).
        let source =
            scaffold_project_workspace(key, "Calculator", "apps", Some("node"), None).await
                .expect("re-scaffold");
        assert_eq!(source, ScaffoldSource::Existing);

        let _ = std::fs::remove_dir_all(&tmp);
        crate::harness::restore_workspace_root(previous);
        match previous_llm {
            Some(v) => std::env::set_var("LLM_URL", v),
            None => std::env::remove_var("LLM_URL"),
        }
        match previous_key {
            Some(v) => std::env::set_var("LLM_KEY", v),
            None => std::env::remove_var("LLM_KEY"),
        }
    }

    #[test]
    fn rejects_unsafe_paths() {
        let mut map = serde_json::Map::new();
        map.insert("../evil".into(), serde_json::Value::String("x".into()));
        assert!(write_files("p", &map).is_err());
        map.clear();
        map.insert("/abs".into(), serde_json::Value::String("x".into()));
        assert!(write_files("p", &map).is_err());
        map.clear();
        map.insert("ok.js".into(), serde_json::Value::String("x".into()));
        assert!(write_files("p", &map).is_ok());
    }
}