data_directory = '/home/a404010/src/generalbots/botserver/botserver-stack/data/tables/pgdata'
ident_file = '/home/a404010/src/generalbots/botserver/botserver-stack/conf/pg_ident.conf'
port = 5432
listen_addresses = '*'
ssl = on
ssl_cert_file = '/home/a404010/src/generalbots/botserver/botserver-stack/conf/system/certificates/tables/server.crt'
ssl_key_file = '/home/a404010/src/generalbots/botserver/botserver-stack/conf/system/certificates/tables/server.key'
ssl_ca_file = '/home/a404010/src/generalbots/botserver/botserver-stack/conf/system/certificates/ca/ca.crt'
log_directory = '/home/a404010/src/generalbots/botserver/botserver-stack/logs/tables'
logging_collector = on
