ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS name VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS schedule VARCHAR(255);
ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS task_type VARCHAR(100) NOT NULL DEFAULT 'scheduled';
ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS config JSONB;
ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE auto_tasks ADD COLUMN IF NOT EXISTS last_run_at TIMESTAMPTZ;