-- Collapsed into 6.2.1-01-core (#1347).
--
-- This migration's up.sql was byte-identical to 6.2.1-01-core/up.sql, so on a
-- fresh install the same SQL ran twice (harmlessly — the statements are
-- idempotent). This file is now a no-op stub:
--
--   * Databases that already applied it carry the recorded version, so the
--     content is never re-read and nothing changes for them.
--   * Fresh installs run this stub and then the real statements from
--     6.2.1-01-core, reaching the identical final schema.
--
-- The real statements (refresh_policy column on website_crawls, backfill and
-- comment) live in 6.2.1-01-core/up.sql only.
SELECT 1;
